### ISSUE TITLE
more fish types other than demonfish

### ISSUE THREAD

**Issue by LukyLucas** [MineInAbyss/Issue-Tracker#109]
### Mob name

Fancy poisfish

### Spawn Locations

edge and goblets less common in sea of corpses

### Mob-type

Water / Fish

### Mob Info

pretty much a pufferfish with some extra drops and a new texture.

### Mob Model/Texture

if i make the texture itll look like a fancy goldfish with stripes and spikes but more vibrant colors like purple orange and white.

### Related mobdrop ideas

drops poisoned meat, like rotten flesh but worse, drops 2-3 poison spikes which could be used for poison arrows that apply deadly poison (the one that can actually kill them) but that might be too op in fights idk. had an idea for a elastic skin drop which could be used to craft the balloons delvers send up.

### Additional info

I'm willing to do textures for this or any additional work for the mob let me know if I'm needed.

right now im talking about like a actual mob that swims around but had an idea for a fishing drop where you can get the whole fish and if you put it in the crafting table with a dagger you can get the meat unpoisoned like at a fancy restaurant.

### Agreements

- [X] I have searched for and ensured there isn't already an open suggestion similar to this.
- [X] I have ensured the mob I'm suggesting isn't already on the server.

**Comment by LukyLucas** [comment]
not high priority because it would be better in adventure

**Comment by VaIienta** [comment]
Kinda just sounds like an orb piercer but a fish, have you considered behaviours as well? For a mob that drops some useful items it should probably have some more interesting behaviours that make these harder to get.

**Comment by LukyLucas** [comment]
I don't want it to be like a orb piercer cause those things are just too op. It would be small like a salmon but would still be evasive by small hitbox and aggressive to players. Unlike orbies of they find each other they would form a school almost like piranhas would

**Comment by VaIienta** [comment]
That sounds more _**annoying**_ that making an _**interesting**_ behaviour, the idea of the fish grouping up is somewhat interesting but that's really just them spawning in groups and all becoming aggressive at once like Kuon's for example. You've mentioned poisonous spikes but haven't really related that back to the mob - it doesn't inherently mean it needs to be aggressive either, it could be extremely defensive and use them to it's advantage. If this mob is better suited for adventure then it's worthwhile really thinking through its behaviours as well because we will be able to do a lot more down the road hopefully.
