### ISSUE TITLE
extra music- ambient soundtracks and battle music.

### ISSUE THREAD

**Issue by LukyLucas** [MineInAbyss/Issue-Tracker#112]
### Is your feature request related to a problem?

just would be good if added.

### Describe the solution you'd like.

ambient soundtracks can be cut out the anime and looped. do this to a couple and add them to the files. for battle music its a bit more complex due to there might be coding in play.

### Describe alternatives you've considered.

i can do this myself since its not high priority. i just need the greenlight from boy.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Naatchi** [comment]
we legally cant do this

**Comment by LukyLucas** [comment]
It can be added as downloadable content in the Launcher though right?

**Comment by Boy0000** [comment]
We are already bordering on copyright violation, only being fine because its not straight stealing.

We wont use any part ripped from the show, but remaking stuff with noteblocks is fine

Ambient etc is not just make song and /play, it needs an entire system that ties in with layers/locations/scenarios etc
