### ISSUE TITLE
Unsynchronized sections

### ISSUE THREAD

**Issue by 0ffz** [MineInAbyss/Issue-Tracker#37]
Some sections have differing blocks between them, so going between two sections may sometimes result in death, or odd looking differences.

As a quick solution, we could add a command to DeeperWorld, which could sync an area around a radius of the player to the section above or below using Worldedit's API.

Please use this thread to keep track of specific areas (include coordinates) which have severe missing blocks. For example, a missing goblet in layer 4.

**Comment by DatVeno** [comment]
l3s7 and l4s1 is completly desynced

![2020-02-10_09 12 00](https://user-images.githubusercontent.com/38132190/74131954-d288dc00-4be5-11ea-9701-0a2dfcf1db8e.png)
![2020-02-10_09 12 28](https://user-images.githubusercontent.com/38132190/74131963-d4eb3600-4be5-11ea-8ba0-2e5d3b445e59.png)

Also you can destroy the signs when changing sections because of the desync
![2020-02-10_09 15 36](https://user-images.githubusercontent.com/38132190/74132089-17147780-4be6-11ea-9022-7033ce809a9b.png)
![2020-02-10_09 16 14](https://user-images.githubusercontent.com/38132190/74132093-1845a480-4be6-11ea-868a-a9882ba59239.png)

**Comment by Mayonnaise5324** [comment]
This doesnt completely entitle that the sections are desynced, but more you built right where the sections are most unstable. Building below a Y of 30 or above 220 in sections means builds can get really messed up. Desynced means the physical structure of the abyss itself is messed up, not your blocks. Say theres a tunnel in s7, that should exit out in s1. If those tunnels don't link, then there's a desync.

**Comment by Derongan** [comment]
Crops are expected to be desynced at the moment, so thats not a big issue. Chests also should not be put near a border for this very reason

**Comment by DatVeno** [comment]
Issue would be solved by moving the teleport from l4s1 from Y241 to Y222. Then the teleport would be porperly synced to l3s7

**Comment by LowLucifer** [comment]
Hello ! 

Got a problem on the survival server...

i dig a hole for a minecart system for me and my friend between L2 and L4.
When i reacher L3S6 i enter in a special area with only coal block and obsidian, then i continue to dig and when i change of zone i arrive in L3S5... and not in L3S7...

then i try to go up (come back on my step), but i'm not teleport and i can walk on the "Roof" of the section :

![efqedfqvfzeq](https://user-images.githubusercontent.com/71601205/93715899-7d924880-fb6c-11ea-8bfb-42aa9ec67f30.png)

I think it's a problem of synchronisation between this 2 levels...

L3S6 :

![bug minecraft 1](https://user-images.githubusercontent.com/71601205/93715733-761e6f80-fb6b-11ea-8bc9-55b957a26361.png)

L3S5 (after going down of L3S6) :

![bug minecraft 2](https://user-images.githubusercontent.com/71601205/93715742-7a4a8d00-fb6b-11ea-92c0-ca94e831036c.png)
