### ISSUE TITLE
Curse to harsh in layer 5 at this rate

### ISSUE THREAD

**Issue by TheSkyfox1** [MineInAbyss/Issue-Tracker#43]
There has been alot of changes made to the curse.
Now we are at a state where many agree that the curse is to harsh again.
Now climbing is almost impossible, wither 2 kills you faster then you can heal with eating, railways
unuseable. Building high stuff is basically impossible without wither effect and lags make it even
harder to compensate the wither effect. I would say that wither 1 was fine as it was. Right now it is 
bareably playable on l5.

**Comment by malwilson** [comment]
Im not seeing what you are describing as impossible, even without full diamond armor im only getting hit 2-3 hearts of damage while going up 100 blocks. maybe you are eating something different as im only eating raw carrots, as i also dont get the faster damage than you can heal thing.
[![testing](https://img.youtube.com/vi/ukOUejjxQYw/0.jpg)](https://www.youtube.com/watch?v=ukOUejjxQYw)

Im also not too sure what you mean by railways being unuseable are you going straight up in a minecart? try going up gradually instead of elevatoring yourself to death.
The fact that you didnt get cursed while riding something was always a bug.

Long and short my thought is that you shouldent be able to go down to level 5 without any preparation,any armor,tools or even any cooked food. and be able to just jump in a elevator and go up to level 4 in 40 seconds without worying about the damage recieved or effects of the curse.
if the curse does nothing even at the hardest level why even have the curse

**Comment by TheSkyfox1** [comment]
I am using bread as food, and I see the problem with people jumping down but all the minecarts that existed are now unuseable because its almost impossible to fight against a 2 min curse. Also it annoys building to an ass rate. I kinda grew used to the curse now but I am still not a fan of it in l5,

**Comment by TheSkyfox1** [comment]
https://youtu.be/Y7QQvdGYePU

**Comment by Boy0000** [comment]
fixed
