### ISSUE TITLE
getting netherstar from mining

### ISSUE THREAD

**Issue by pandawanda223** [MineInAbyss/Issue-Tracker#99]
### Is your feature request related to a problem?

not having beacons in the game

### Describe the solution you'd like.

when you mine you have a very very very small chance to get a nether star. People will not live to get it at the end not get it to complain, try again in a couple of days. Rinse and repeat is, a great way to keep the players who kinda lost purpose in playing on the server to do something. And I know you guys wanna do something related to boss fights, but I just don't see why, you have all these plans for adventure, but then put those same plans onto survival, making survival and adventure the same.

### Describe alternatives you've considered.

new ores which in the process have the same effect as the % chance to get a nether star but make room for different things, such as stronger mobs and stuff. with these new ores, you could make a beacon

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Boy0000** [comment]
Netherstar wont be gotten from just sitting there mining for 200 hours no
It is a boring grind that "gives old players that lost interest something to do".
If what you want is to mindlessly mine for ages just so you can craft a block that lets you, mine faster?

If any feature like it is to be added, its gonna be through not boring ass shitty gameplay loops designed to make people just stay. Focus has, as mentioned before, shifted away from survival and onto adventure cuz otherwise no progress at all is done.
Case in point we had no progress on adventure from August 2020 to August 2021 because we kept focusing on adding to survival.

Features will come on survival as they are implemented and in a relevant way. We wont spend time making a mindless system that wont be carried over. If you wanna further give ideas onto how beacons and nether stars etc could be implemented, there is currently #80 you could add ideas to. But again we wont add beacons, tridents etc just so people "have something to do".

**Comment by pandawanda223** [comment]
But that is the problem there is nothing to build on, everything is easy to get on the server. So there currently is no way of giving a recipe for nether stars. And I understand you knew that from the moment u asked to recommend a recipe. so at this point doing suggestions is just a waste of time.

**Comment by Boy0000** [comment]
If your suggestion is simply "make this item obtained with a 0.000000000000001% change from mining because i want it" then yes it is a waste of time

if youre making a good suggestion it usually gets accepted. Look at Csig. He has made several suggestions for recipes that have been added.
1. Because they werent really planned to be done much with
2. He made the config and everything himself
3. They were otherwise primarily obtained from merchants in Orth

Beacons are a tad bit different i would say. Just because your 1 suggestion got denied doesnt mean there is no point...
And just because you make a suggestion doesnt mean it is 100% gonna be implemented in that way.
Usually for bigger ideas, like beacons, parts are taken from several suggestions thus changing the final implementation.

And yes there is nothing that really is "hard to obtain" outside of finding it in the map naturally etc
Hence we are working on improving systems to improve this and not adding it just from mining with a % of 0.0000000001 just so its there.

**Comment by 0ffz** [comment]
Keep in mind, even denied suggestions are useful for reference in the future so the discussion isn't repeated or points forgotten.

Just to add on, personally I think extremely low probability is generally a sign of side-stepping a proper solution. Like boy said, mining isn't particularly interesting gameplay and the fact that the reward is being able to mine faster in the future *really* screams grind.
